// This file will be auto-generated by: npx supabase gen types typescript --local
// For now, provide a minimal type stub so the app compiles.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          display_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          unit_system: 'metric' | 'imperial';
          date_of_birth: string | null;
          gender: 'male' | 'female' | 'other' | null;
          height_cm: number | null;
          weight_kg: number | null;
          fitness_level: 'beginner' | 'intermediate' | 'advanced' | 'expert' | null;
          is_premium: boolean;
          streak_count: number;
          longest_streak: number;
          onboarding_completed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username: string;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          unit_system?: 'metric' | 'imperial';
          date_of_birth?: string | null;
          gender?: 'male' | 'female' | 'other' | null;
          height_cm?: number | null;
          weight_kg?: number | null;
          fitness_level?: 'beginner' | 'intermediate' | 'advanced' | 'expert' | null;
          is_premium?: boolean;
          streak_count?: number;
          longest_streak?: number;
          onboarding_completed?: boolean;
        };
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
      };
      exercises: {
        Row: {
          id: string;
          name: string;
          gif_url: string | null;
          instructions: string[] | null;
          equipment: string[];
          body_parts: string[];
          target_muscles: string[];
          secondary_muscles: string[];
          exercise_type: string | null;
          mechanics_type: string | null;
          is_custom: boolean;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          gif_url?: string | null;
          instructions?: string[] | null;
          equipment?: string[];
          body_parts?: string[];
          target_muscles?: string[];
          secondary_muscles?: string[];
          exercise_type?: string | null;
          mechanics_type?: string | null;
          is_custom?: boolean;
          created_by?: string | null;
        };
        Update: Partial<Database['public']['Tables']['exercises']['Insert']>;
      };
      workout_templates: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          category: string | null;
          is_public: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          category?: string | null;
          is_public?: boolean;
        };
        Update: Partial<Database['public']['Tables']['workout_templates']['Insert']>;
      };
      workout_sessions: {
        Row: {
          id: string;
          user_id: string;
          template_id: string | null;
          name: string | null;
          started_at: string;
          ended_at: string | null;
          duration_s: number | null;
          rating: number | null;
          notes: string | null;
          is_synced: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          template_id?: string | null;
          name?: string | null;
          started_at?: string;
          ended_at?: string | null;
          duration_s?: number | null;
          rating?: number | null;
          notes?: string | null;
          is_synced?: boolean;
        };
        Update: Partial<Database['public']['Tables']['workout_sessions']['Insert']>;
      };
      session_exercises: {
        Row: {
          id: string;
          session_id: string;
          exercise_id: string;
          sort_order: number;
        };
        Insert: {
          id?: string;
          session_id: string;
          exercise_id: string;
          sort_order?: number;
        };
        Update: Partial<Database['public']['Tables']['session_exercises']['Insert']>;
      };
      exercise_sets: {
        Row: {
          id: string;
          session_exercise_id: string;
          set_index: number;
          set_type: string;
          weight: number | null;
          weight_unit: string | null;
          reps: number | null;
          duration_s: number | null;
          distance_m: number | null;
          completed: boolean;
          rpe: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          session_exercise_id: string;
          set_index: number;
          set_type?: string;
          weight?: number | null;
          weight_unit?: string | null;
          reps?: number | null;
          duration_s?: number | null;
          distance_m?: number | null;
          completed?: boolean;
          rpe?: number | null;
        };
        Update: Partial<Database['public']['Tables']['exercise_sets']['Insert']>;
      };
      daily_metrics: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          steps: number | null;
          water_ml: number | null;
          calories_in: number | null;
          calories_burned: number | null;
          weight_kg: number | null;
          body_fat_pct: number | null;
          sleep_minutes: number | null;
          hr_resting: number | null;
          hrv: number | null;
          notes: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          steps?: number | null;
          water_ml?: number | null;
          calories_in?: number | null;
          calories_burned?: number | null;
          weight_kg?: number | null;
          body_fat_pct?: number | null;
          sleep_minutes?: number | null;
          hr_resting?: number | null;
          hrv?: number | null;
          notes?: string | null;
        };
        Update: Partial<Database['public']['Tables']['daily_metrics']['Insert']>;
      };
      meals: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          calories: number | null;
          protein_g: number | null;
          carbs_g: number | null;
          fat_g: number | null;
          category: string | null;
          logged_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          calories?: number | null;
          protein_g?: number | null;
          carbs_g?: number | null;
          fat_g?: number | null;
          category?: string | null;
          logged_at?: string;
        };
        Update: Partial<Database['public']['Tables']['meals']['Insert']>;
      };
      personal_records: {
        Row: {
          id: string;
          user_id: string;
          exercise_id: string | null;
          name: string;
          record_type: 'weight' | 'reps' | 'time' | 'distance';
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          exercise_id?: string | null;
          name: string;
          record_type: 'weight' | 'reps' | 'time' | 'distance';
        };
        Update: Partial<Database['public']['Tables']['personal_records']['Insert']>;
      };
      pr_values: {
        Row: {
          id: string;
          pr_id: string;
          value: number;
          unit: string | null;
          recorded_at: string;
        };
        Insert: {
          id?: string;
          pr_id: string;
          value: number;
          unit?: string | null;
          recorded_at?: string;
        };
        Update: Partial<Database['public']['Tables']['pr_values']['Insert']>;
      };
      feed_posts: {
        Row: {
          id: string;
          user_id: string;
          post_type: string;
          session_id: string | null;
          pr_id: string | null;
          content: string | null;
          media_url: string | null;
          visibility: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          post_type: string;
          session_id?: string | null;
          pr_id?: string | null;
          content?: string | null;
          media_url?: string | null;
          visibility?: string;
        };
        Update: Partial<Database['public']['Tables']['feed_posts']['Insert']>;
      };
      friendships: {
        Row: {
          id: string;
          requester_id: string;
          addressee_id: string;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          requester_id: string;
          addressee_id: string;
          status?: string;
        };
        Update: Partial<Database['public']['Tables']['friendships']['Insert']>;
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          body: string | null;
          data: Json | null;
          read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title: string;
          body?: string | null;
          data?: Json | null;
          read?: boolean;
        };
        Update: Partial<Database['public']['Tables']['notifications']['Insert']>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
